Update manifest version and add webstore link
gnosis/zodiac-pilot pull request #24
Opened 2022-09-14 04:43 UTC by samepant

The Zodiac Pilot extension is now available in the webstore, this adds the link to the readme. This also adds the latest release version to the `public/manifest.json` file so the published version matches the repo.

2022-09-14 09:12 UTC, jfschwarz requested changes

2022-09-14 09:12 UTC, jfschwarz commented on public/manifest.json
> +  "version": "1.1.5",
Actually, this is already automated in the prod release workflow: https://github.com/gnosis/zodiac-pilot/blob/main/.github/workflows/prod-release.yaml#L20

2022-09-14 09:12 UTC, jfschwarz commented on public/manifest.json
> +  "version": "1.1.5",
```suggestion
  "version": "0.0.0",
```

2022-09-14 15:22 UTC, samepant commented on public/manifest.json
> +  "version": "1.1.5",
whoops, i think i committed that too 🙃

2022-09-15 07:02 UTC, jfschwarz approved these changes

2022-09-15 07:02 UTC, merged